// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Generated by tools/update_server.py keygen. Test identity only: the
// private key is in test/updater/crx_test_key.json. Sub-project D replaces both.

#ifndef GHOST_BRANDING_CRX_PUBLISHER_KEY_H_
#define GHOST_BRANDING_CRX_PUBLISHER_KEY_H_

#include <stdint.h>

#include <array>

namespace ghost {

// SHA-256 of the DER SubjectPublicKeyInfo of the key whose proof
// CRX3_WITH_GHOST_PUBLISHER_PROOF requires (patches/0018).
inline constexpr std::array<uint8_t, 32> kCrxPublisherKeyHash = {
    0xc3, 0xfc, 0x14, 0xd7, 0xc6, 0x8b, 0xc7, 0x6a, 0x21, 0x3a, 0x24, 0x2a,
    0x9a, 0x73, 0x95, 0xaa, 0x94, 0xf0, 0x33, 0xa0, 0x44, 0xea, 0xd5, 0xe3,
    0xe5, 0x4a, 0x0e, 0x06, 0x29, 0x33, 0x09, 0x68,
};

}  // namespace ghost

#endif  // GHOST_BRANDING_CRX_PUBLISHER_KEY_H_
