#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""Creates a Chromium checkout at the pinned tag with this repo at src/ghost.

Resulting layout (the same shape Brave uses for src/brave):
  <root>/.gclient
  <root>/depot_tools/
  <root>/src/          Chromium at CHROMIUM_COMMIT (the commit of tag CHROMIUM_VERSION)
  <root>/src/ghost/    a clone of this repository; the working copy for development

Every step is safe to re-run. --dry-run prints the exact commands without
touching the disk.

Usage: python tools/bootstrap.py --root D:\\ghost [--dry-run] [--jobs N] [--pgo]
"""

from __future__ import annotations

import argparse
import os
import pprint
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import check_env
import repo

CHROMIUM_URL = "https://chromium.googlesource.com/chromium/src.git"
DEPOT_TOOLS_URL = "https://chromium.googlesource.com/chromium/tools/depot_tools.git"
GHOST_EXCLUDE_LINE = "/ghost/"


class BootstrapError(Exception):
    pass


@dataclass(frozen=True)
class Step:
    description: str
    argv: tuple[str, ...] = ()
    cwd: Path | None = None
    write: tuple[Path, str] | None = None
    append_line: tuple[Path, str] | None = None
    # (repository, ref, expected commit): fail unless ref resolves to the commit.
    verify_ref: tuple[Path, str, str] | None = None

    def render(self) -> str:
        if self.write:
            return f"write {self.write[0]}"
        if self.verify_ref:
            repo_dir, ref, commit = self.verify_ref
            return f"check that {ref} in {repo_dir} is {commit}"
        if self.append_line:
            return f"append {self.append_line[1]!r} to {self.append_line[0]} (if absent)"
        where = f"(in {self.cwd}) " if self.cwd else ""
        return where + subprocess.list2cmdline(self.argv)


def render_gclient(chromium_url: str, ghost_url: str, pgo: bool) -> str:
    # Both solutions are unmanaged so `gclient sync` never resets local
    # branches; the Chromium revision is pinned on the command line instead.
    solutions = [
        {"name": "src", "url": chromium_url, "managed": False, "custom_deps": {},
         # PGO profiles are only needed for official (release) builds.
         "custom_vars": {"checkout_pgo_profiles": pgo}},
        {"name": "src/ghost", "url": ghost_url, "managed": False, "custom_deps": {},
         "custom_vars": {}},
    ]
    return ("# Generated by ghost/tools/bootstrap.py. Re-running bootstrap overwrites it.\n"
            f"solutions = {pprint.pformat(solutions, sort_dicts=False)}\n"
            "target_os = ['win']\n")


def gclient_path(depot_tools: Path) -> Path:
    return depot_tools / ("gclient.bat" if sys.platform == "win32" else "gclient")


def plan(root: Path, version: str, commit: str, ghost_url: str, depot_tools: Path,
         have_depot_tools: bool, have_src: bool, jobs: int, pgo: bool) -> list[Step]:
    gclient = str(gclient_path(depot_tools))
    src = root / "src"
    tag = f"refs/tags/{version}"
    fetch_tag = Step(f"Fetch tag {version} (shallow)",
                     ("git", "-C", str(src), "fetch", "--depth=1", "--no-tags", "origin",
                      f"+{tag}:{tag}"))
    verify_tag = Step(f"Check that tag {version} is the pinned commit {commit[:12]}",
                      verify_ref=(src, tag, commit))
    steps = []
    if not have_depot_tools:
        steps.append(Step("Clone depot_tools",
                          ("git", "clone", DEPOT_TOOLS_URL, str(depot_tools))))
    steps.append(Step("Write .gclient",
                      write=(root / ".gclient", render_gclient(CHROMIUM_URL, ghost_url, pgo))))
    # gclient is given the commit hash, not the tag. It skips its fetch of
    # every upstream branch only when the revision is a hash already present
    # locally (IsValidRevision(..., sha_only=True) in gclient_scm.py). On a
    # shallow checkout that fetch can run for hours without output, which
    # looks exactly like a hang. An existing checkout therefore gets the tag
    # first; a fresh one is cloned at the hash directly.
    if have_src:
        steps += [fetch_tag, verify_tag]
    steps.append(Step(f"Sync Chromium {version} and src/ghost (first run takes over an hour)",
                      (gclient, "sync", "--nohooks", "--no-history",
                       "--revision", f"src@{commit}", "--jobs", str(jobs)), cwd=root))
    if not have_src:
        steps += [fetch_tag, verify_tag]
    steps += [
        Step("Run gclient hooks (toolchains, PGO profiles if enabled)",
             (gclient, "runhooks"), cwd=root),
        # src/ghost lives inside Chromium's working tree but is its own repo.
        Step("Hide src/ghost from Chromium's git status",
             append_line=(src / ".git" / "info" / "exclude", GHOST_EXCLUDE_LINE)),
    ]
    return steps


def validate_root(root: Path, volume: check_env.VolumeFacts, req: dict,
                  env: dict[str, str]) -> list[str]:
    problems = []
    if not root.is_absolute():
        problems.append(f"{root} is not an absolute path")
    if " " in str(root):
        problems.append(f"{root} contains a space; Chromium requires a path without spaces")
    for var in ("OneDrive", "OneDriveConsumer", "OneDriveCommercial"):
        synced = env.get(var)
        if synced and _is_within(root, Path(synced)):
            problems.append(f"{root} is inside {var} ({synced}); sync clients corrupt "
                            "large checkouts and slow every build")
    win = req["windows"]
    if volume.filesystem not in win["filesystems"]:
        problems.append(f"{root} is on {volume.filesystem or 'an unknown filesystem'}; "
                        f"use {' or '.join(win['filesystems'])}")
    if volume.free_gb < win["disk_free_gb"]["minimum"]:
        problems.append(f"only {volume.free_gb:.0f} GB free; at least "
                        f"{win['disk_free_gb']['minimum']} GB is required")
    return problems


def _is_within(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def default_ghost_url(repo_root: Path = repo.REPO_ROOT) -> str:
    """The origin remote if configured, else this checkout as a file:// URL."""
    proc = subprocess.run(["git", "-C", str(repo_root), "remote", "get-url", "origin"],
                          capture_output=True, text=True)
    if proc.returncode == 0 and proc.stdout.strip():
        return proc.stdout.strip()
    return repo_root.resolve().as_uri()


def execute(step: Step, env: dict[str, str]) -> None:
    if step.write:
        path, content = step.write
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    elif step.append_line:
        path, line = step.append_line
        existing = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
        if line not in existing:
            with path.open("a", encoding="utf-8", newline="\n") as f:
                f.write(line + "\n")
    elif step.verify_ref:
        repo_dir, ref, expected = step.verify_ref
        proc = subprocess.run(["git", "-C", str(repo_dir), "rev-parse", "--verify", "--quiet",
                               f"{ref}^{{commit}}"], capture_output=True, text=True, env=env)
        actual = proc.stdout.strip()
        if actual != expected:
            raise BootstrapError(
                f"{ref} resolves to {actual or 'nothing'}, but CHROMIUM_COMMIT pins {expected}. "
                "Either the upstream tag moved or the pin is wrong; do not build until "
                "this is explained.")
    else:
        subprocess.run(step.argv, cwd=step.cwd, env=env, check=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", required=True, type=Path,
                        help="checkout root, e.g. D:\\ghost (no spaces, on a Dev Drive ideally)")
    parser.add_argument("--depot-tools", type=Path,
                        help="existing depot_tools directory (default: <root>/depot_tools)")
    parser.add_argument("--ghost-url", help="URL gclient clones into src/ghost "
                        "(default: this repo's origin, else this checkout)")
    parser.add_argument("--jobs", type=int, default=os.cpu_count() or 8)
    parser.add_argument("--pgo", action="store_true",
                        help="download PGO profiles (needed for official builds only)")
    parser.add_argument("--dry-run", action="store_true", help="print the plan and exit")
    args = parser.parse_args(argv)

    req = repo.load_requirements()
    version = repo.read_chromium_version()
    commit = repo.read_chromium_commit()
    root = args.root
    depot_tools = args.depot_tools or root / "depot_tools"
    steps = plan(root, version, commit, args.ghost_url or default_ghost_url(), depot_tools,
                 have_depot_tools=gclient_path(depot_tools).exists(),
                 have_src=(root / "src" / ".git").exists(), jobs=args.jobs, pgo=args.pgo)

    problems = validate_root(root, check_env.probe_volume(str(root)), req, dict(os.environ))
    for problem in problems:
        print(f"{'warning' if args.dry_run else 'error'}: {problem}", file=sys.stderr)
    if problems and not args.dry_run:
        return 1

    print(f"Bootstrapping Chromium {version} into {root}")
    for i, step in enumerate(steps, 1):
        print(f"[{i}/{len(steps)}] {step.description}\n        {step.render()}")
    if args.dry_run:
        return 0

    env = dict(os.environ, DEPOT_TOOLS_WIN_TOOLCHAIN="0")
    env["PATH"] = str(depot_tools) + os.pathsep + env.get("PATH", "")
    root.mkdir(parents=True, exist_ok=True)
    for i, step in enumerate(steps, 1):
        print(f"\n==> [{i}/{len(steps)}] {step.description}", flush=True)
        try:
            execute(step, env)
        except subprocess.CalledProcessError as e:
            print(f"error: step {i} failed with exit code {e.returncode}; "
                  "fix the cause and re-run (completed steps are skipped or harmless)",
                  file=sys.stderr)
            return e.returncode or 1
        except BootstrapError as e:
            print(f"error: step {i}: {e}", file=sys.stderr)
            return 1
    print("\nDone. Next: python tools/check_env.py --build-root", root)
    return 0


if __name__ == "__main__":
    sys.exit(main())
