#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""Writes a text file into a C++ header as a raw string constant (a GN action).

    embed_text.py --input data/list.txt --output gen/list.h --namespace ns --name kList

Line endings become LF, so a checkout's autocrlf can't change the binary.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DELIMITER = "embed"


def render(text: str, namespace: str, name: str, output: str, source: str) -> str:
    if f'){DELIMITER}"' in text:
        raise ValueError(f'{source} contains ){DELIMITER}", which would end the raw string')
    guard = re.sub(r"[^A-Za-z0-9]", "_", output).upper() + "_"
    return (f"// Generated by //ghost/tools/embed_text.py from {source}. Don't edit.\n\n"
            f"#ifndef {guard}\n#define {guard}\n\n"
            f"namespace {namespace} {{\n\n"
            f'inline constexpr char {name}[] = R"{DELIMITER}({text}){DELIMITER}";\n\n'
            f"}}  // namespace {namespace}\n\n#endif  // {guard}\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    for flag in ("--input", "--output", "--namespace", "--name"):
        parser.add_argument(flag, required=True)
    args = parser.parse_args(argv)
    text = Path(args.input).read_bytes().decode("utf-8").replace("\r\n", "\n")
    Path(args.output).write_text(
        render(text, args.namespace, args.name, Path(args.output).as_posix(),
               Path(args.input).as_posix()), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
